### ISSUE TITLE
App crashes when "cf push" is done through jenkins

### ISSUE THREAD

**Issue by erindas** [swilliams11/apigee-microgateway-bluemix#1]
When I try to deploy this gateway-app using jenkins build "cf push" command. App startup fails with below error. If I do the "cf push" from my computer.. it works fine.

Any idea how to fix this???

 2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── commander@2.20.0
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── config@1.31.0
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── cpr@1.1.2
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── debug@2.6.9
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── diff@3.5.0
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── forever-monitor@1.7.1
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── fs-extra@0.20.1
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── js-yaml@3.13.0
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── jsonwebtoken@5.7.0
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── lodash@3.10.1
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── log-symbols@1.0.2
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── memored@1.1.1
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── microgateway-config@2.4.17
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── microgateway-core@2.5.14
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── microgateway-edgeauth@2.4.13
   2019-05-17T16:27:19.50-0500 [STG/0] OUT        ├── microgateway-plugins@2.3.31
   2019-05-17T16:27:19.51-0500 [STG/0] OUT        ├── pem@1.14.2
   2019-05-17T16:27:19.51-0500 [STG/0] OUT        ├── portastic@1.0.1
   2019-05-17T16:27:19.51-0500 [STG/0] OUT        ├── request@2.88.0
   2019-05-17T16:27:19.51-0500 [STG/0] OUT        ├── rimraf@2.6.3
   2019-05-17T16:27:19.51-0500 [STG/0] OUT        ├── tmp@0.0.28
   2019-05-17T16:27:19.51-0500 [STG/0] OUT        ├── uuid@3.3.2
   2019-05-17T16:27:19.51-0500 [STG/0] OUT        ├── volos-cache-memory@0.10.1
   2019-05-17T16:27:19.51-0500 [STG/0] OUT        ├── volos-spikearrest-common@0.10.3
   2019-05-17T16:27:19.51-0500 [STG/0] OUT        ├── volos-spikearrest-memory@0.10.1
   2019-05-17T16:27:19.51-0500 [STG/0] OUT        └── xml2js@0.4.19
   2019-05-17T16:27:19.51-0500 [STG/0] OUT
   2019-05-17T16:27:35.70-0500 [STG/0] OUT Exit status 0
   2019-05-17T16:27:35.70-0500 [STG/0] OUT Uploading droplet, build artifacts cache...
   2019-05-17T16:27:35.70-0500 [STG/0] OUT Uploading droplet...
   2019-05-17T16:27:35.70-0500 [STG/0] OUT Uploading build artifacts cache...
   2019-05-17T16:27:36.09-0500 [STG/0] OUT Uploaded build artifacts cache (7.2M)
   2019-05-17T16:27:36.67-0500 [API/16] OUT Creating droplet for app with guid cfc9d457-f4c5-4202-9efa-93062f6e136c
   2019-05-17T16:27:42.98-0500 [STG/0] OUT Uploaded droplet (30.6M)
   2019-05-17T16:27:42.99-0500 [STG/0] OUT Uploading complete
   2019-05-17T16:27:43.61-0500 [STG/0] OUT Cell f6019044-bfe2-4249-b7f5-5f40ee22f2c5 stopping instance 9224caf6-251b-492b-90c2-ecba833f0e1d
   2019-05-17T16:27:43.61-0500 [STG/0] OUT Cell f6019044-bfe2-4249-b7f5-5f40ee22f2c5 destroying container for instance 9224caf6-251b-492b-90c2-ecba833f0e1d
   2019-05-17T16:27:44.67-0500 [CELL/0] OUT Cell faf26a54-a016-4c7b-813c-76e2d0716170 creating container for instance f20d51c3-bb44-4382-78fb-3ddf
   2019-05-17T16:27:45.99-0500 [CELL/0] OUT Cell faf26a54-a016-4c7b-813c-76e2d0716170 successfully created container for instance f20d51c3-bb44-4382-78fb-3ddf
   2019-05-17T16:27:46.83-0500 [STG/0] OUT Cell f6019044-bfe2-4249-b7f5-5f40ee22f2c5 successfully destroyed container for instance 9224caf6-251b-492b-90c2-ecba833f0e1d
   2019-05-17T16:27:51.95-0500 [CELL/0] OUT Starting health monitoring of container
   2019-05-17T16:27:54.52-0500 [APP/PROC/WEB/0] OUT > edgemicro@2.5.16 start /home/vcap/app
   2019-05-17T16:27:54.52-0500 [APP/PROC/WEB/0] OUT > node app.js
   

> 2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR config does not exist /app/erinadas-eval-test-config.yaml
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/microgateway-config/lib/io.js:73
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     throw new Error('config does not exist');
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     ^
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR Error: config does not exist
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at IO.loadSync (/home/vcap/app/node_modules/microgateway-config/lib/io.js:73:11)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at Loader.get (/home/vcap/app/node_modules/microgateway-config/lib/network.js:96:35)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at Object.get (/home/vcap/app/node_modules/microgateway-config/index.js:16:30)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at Gateway.start.e [as start] (/home/vcap/app/cli/lib/gateway.js:52:16)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/app/app.js:64:7)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:577:32)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:586:10)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at Module.load (module.js:494:32)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at tryModuleLoad (module.js:453:12)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:445:3)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at Module.runMain (module.js:611:10)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at run (bootstrap_node.js:394:7)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at startup (bootstrap_node.js:160:9)
>    2019-05-17T16:27:56.08-0500 [APP/PROC/WEB/0] ERR     at bootstrap_node.js:507:3
>    2019-05-17T16:27:56.11-0500 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
>    2019-05-17T16:27:56.11-0500 [APP/PROC/WEB/0] ERR npm ERR! errno 1
>    2019-05-17T16:27:56.11-0500 [APP/PROC/WEB/0] ERR npm ERR! edgemicro@2.5.16 start: `node app.js`
>    2019-05-17T16:27:56.11-0500 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
>    2019-05-17T16:27:56.11-0500 [APP/PROC/WEB/0] ERR npm ERR!
>    2019-05-17T16:27:56.12-0500 [APP/PROC/WEB/0] ERR npm ERR! Failed at the edgemicro@2.5.16 start script.
>    2019-05-17T16:27:56.12-0500 [APP/PROC/WEB/0] ERR npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>    2019-05-17T16:27:56.13-0500 [APP/PROC/WEB/0] ERR npm ERR! A complete log of this run can be found in:
>    2019-05-17T16:27:56.13-0500 [APP/PROC/WEB/0] ERR npm ERR!

     /home/vcap/app/.npm/_logs/2019-05-17T21_27_56_125Z-debug.log
   2019-05-17T16:27:56.18-0500 [APP/PROC/WEB/0] OUT Exit status 1
   2019-05-17T16:27:56.19-0500 [CELL/SSHD/0] OUT Exit status 0
   2019-05-17T16:28:01.84-0500 [CELL/0] OUT Cell faf26a54-a016-4c7b-813c-76e2d0716170 stopping instance f20d51c3-bb44-4382-78fb-3ddf
   2019-05-17T16:28:01.84-0500 [CELL/0] OUT Cell faf26a54-a016-4c7b-813c-76e2d0716170 destroying container for instance f20d51c3-bb44-4382-78fb-3ddf
   2019-05-17T16:28:01.86-0500 [API/3] OUT Process has crashed with type: "web"
   2019-05-17T16:28:01.89-0500 [API/3] OUT App instance exited with guid cfc9d457-f4c5-4202-9efa-930

**Comment by erindas** [comment]
identified and fixed the issue
